pipeline {
agent any
    tools {
        jdk 'jdk1.8'
        maven 'localmaven'
    }
    stages{
          stage('maven-build') {
              steps{
                 dir('liquibase') {
                       sh 'mvn clean install'
                 }
              }
          }
     }
}