pipeline {
agent any
    tools {
        jdk 'jdk1.8'
        maven 'localmaven'
    }
    environment {
        db_url = 'jdbc:mysql://localhost:3306/db'
    }
    parameters {
        string(name: 'VERSION', defaultValue: '', description: 'Version To Build the Project')
    }

        stages{
          stage('maven-build') {
              steps{
                 dir('liquibase') {
                       sh 'mvn clean install'
                 }
              }
          }
        stage('unit-test') {
            steps{
                dir('liquibase') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('liquibase_changes') {
            steps{
                dir('liquibase/src/database') {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId:'mysql_cred', usernameVariable: 'db_usr', passwordVariable: 'db_pass']]) {
                        sh '/home/rahul/Tools/database/liquibase-3.8.2/liquibase --username=$db_usr --password=$db_pass --url=$db_url --defaultsFile=liquibase.properties update'
                    }
                }
            }
        }

     }
}